version: "3.9"

services:
   school-api:
      build:
         context: .
         dockerfile: Dockerfile.dev
      container_name: School-API
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/app
      ports:
         - 8000:8000
      env_file:
         - .env
      restart: "on-failure"
      depends_on:
         - postgres-db
      networks:
         - school-api

   postgres-db:
      image: kartoza/postgis:12.0
      ports:
         - 5432:5432
      volumes:
         - postgres_data:/var/lib/postgresql
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASS=${POSTGRES_PASS}
         - POSTGRES_DB=${POSTGRES_DB}
      restart: "on-failure"
      networks:
         - school-api
networks:
   school-api:
      driver: bridge

volumes:
   postgres_data:
